declare const _default: {
    RECEIVED_CATEGORY: "RECEIVED_CATEGORY";
    RECEIVED_CATEGORIES: "RECEIVED_CATEGORIES";
    RECEIVED_CATEGORY_ORDER: "RECEIVED_CATEGORY_ORDER";
    CATEGORY_COLLAPSED: "CATEGORY_COLLAPSED";
    CATEGORY_EXPANDED: "CATEGORY_EXPANDED";
    CATEGORY_DELETED: "CATEGORY_DELETED";
};
export default _default;
