declare const _default: {
    RECEIVED_CLOUD_CUSTOMER: "RECEIVED_CLOUD_CUSTOMER";
    RECEIVED_CLOUD_PRODUCTS: "RECEIVED_CLOUD_PRODUCTS";
    RECEIVED_CLOUD_SUBSCRIPTION: "RECEIVED_CLOUD_SUBSCRIPTION";
    RECEIVED_CLOUD_INVOICES: "RECEIVED_CLOUD_INVOICES";
    RECEIVED_CLOUD_SUBSCRIPTION_STATS: "RECEIVED_CLOUD_SUBSCRIPTION_STATS";
};
export default _default;
