declare const _default: {
    CLEAR_CUSTOM_EMOJIS: "CLEAR_CUSTOM_EMOJIS";
    RECEIVED_CUSTOM_EMOJI: "RECEIVED_CUSTOM_EMOJI";
    RECEIVED_CUSTOM_EMOJIS: "RECEIVED_CUSTOM_EMOJIS";
    DELETED_CUSTOM_EMOJI: "DELETED_CUSTOM_EMOJI";
    CUSTOM_EMOJI_DOES_NOT_EXIST: "CUSTOM_EMOJI_DOES_NOT_EXIST";
};
export default _default;
