declare const _default: {
    UPLOAD_FILES_REQUEST: "UPLOAD_FILES_REQUEST";
    UPLOAD_FILES_SUCCESS: "UPLOAD_FILES_SUCCESS";
    UPLOAD_FILES_FAILURE: "UPLOAD_FILES_FAILURE";
    UPLOAD_FILES_CANCEL: "UPLOAD_FILES_CANCEL";
    RECEIVED_FILES_FOR_SEARCH: "RECEIVED_FILES_FOR_SEARCH";
    RECEIVED_FILES_FOR_POST: "RECEIVED_FILES_FOR_POST";
    RECEIVED_UPLOAD_FILES: "RECEIVED_UPLOAD_FILES";
    RECEIVED_FILE_PUBLIC_LINK: "RECEIVED_FILE_PUBLIC_LINK";
};
export default _default;
