declare const _default: {
    RECEIVED_INCOMING_HOOK: "RECEIVED_INCOMING_HOOK";
    RECEIVED_INCOMING_HOOKS: "RECEIVED_INCOMING_HOOKS";
    DELETED_INCOMING_HOOK: "DELETED_INCOMING_HOOK";
    RECEIVED_OUTGOING_HOOK: "RECEIVED_OUTGOING_HOOK";
    RECEIVED_OUTGOING_HOOKS: "RECEIVED_OUTGOING_HOOKS";
    DELETED_OUTGOING_HOOK: "DELETED_OUTGOING_HOOK";
    RECEIVED_CUSTOM_TEAM_COMMANDS: "RECEIVED_CUSTOM_TEAM_COMMANDS";
    RECEIVED_COMMAND: "RECEIVED_COMMAND";
    RECEIVED_COMMANDS: "RECEIVED_COMMANDS";
    RECEIVED_COMMAND_TOKEN: "RECEIVED_COMMAND_TOKEN";
    DELETED_COMMAND: "DELETED_COMMAND";
    RECEIVED_OAUTH_APP: "RECEIVED_OAUTH_APP";
    RECEIVED_OAUTH_APPS: "RECEIVED_OAUTH_APPS";
    DELETED_OAUTH_APP: "DELETED_OAUTH_APP";
    RECEIVED_DIALOG_TRIGGER_ID: "RECEIVED_DIALOG_TRIGGER_ID";
    RECEIVED_DIALOG: "RECEIVED_DIALOG";
};
export default _default;
