declare const _default: {
    CREATE_JOB_REQUEST: "CREATE_JOB_REQUEST";
    CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS";
    CREATE_JOB_FAILURE: "CREATE_JOB_FAILURE";
    CANCEL_JOB_REQUEST: "CANCEL_JOB_REQUEST";
    CANCEL_JOB_SUCCESS: "CANCEL_JOB_SUCCESS";
    CANCEL_JOB_FAILURE: "CANCEL_JOB_FAILURE";
    GET_JOB_REQUEST: "GET_JOB_REQUEST";
    GET_JOB_SUCCESS: "GET_JOB_SUCCESS";
    GET_JOB_FAILURE: "GET_JOB_FAILURE";
    GET_JOBS_REQUEST: "GET_JOBS_REQUEST";
    GET_JOBS_SUCCESS: "GET_JOBS_SUCCESS";
    GET_JOBS_FAILURE: "GET_JOBS_FAILURE";
    RECEIVED_JOB: "RECEIVED_JOB";
    RECEIVED_JOBS: "RECEIVED_JOBS";
    RECEIVED_JOBS_BY_TYPE: "RECEIVED_JOBS_BY_TYPE";
};
export default _default;
