declare const _default: {
    RECEIVED_PREFERENCES: "RECEIVED_PREFERENCES";
    RECEIVED_ALL_PREFERENCES: "RECEIVED_ALL_PREFERENCES";
    DELETED_PREFERENCES: "DELETED_PREFERENCES";
};
export default _default;
