declare const _default: {
    ROLES_BY_NAMES_REQUEST: "ROLES_BY_NAMES_REQUEST";
    ROLES_BY_NAMES_SUCCESS: "ROLES_BY_NAMES_SUCCESS";
    ROLES_BY_NAMES_FAILURE: "ROLES_BY_NAMES_FAILURE";
    ROLE_BY_NAME_REQUEST: "ROLE_BY_NAME_REQUEST";
    ROLE_BY_NAME_SUCCESS: "ROLE_BY_NAME_SUCCESS";
    ROLE_BY_NAME_FAILURE: "ROLE_BY_NAME_FAILURE";
    ROLE_BY_ID_REQUEST: "ROLE_BY_ID_REQUEST";
    ROLE_BY_ID_SUCCESS: "ROLE_BY_ID_SUCCESS";
    ROLE_BY_ID_FAILURE: "ROLE_BY_ID_FAILURE";
    EDIT_ROLE_REQUEST: "EDIT_ROLE_REQUEST";
    EDIT_ROLE_SUCCESS: "EDIT_ROLE_SUCCESS";
    EDIT_ROLE_FAILURE: "EDIT_ROLE_FAILURE";
    RECEIVED_ROLES: "RECEIVED_ROLES";
    RECEIVED_ROLE: "RECEIVED_ROLE";
    ROLE_DELETED: "ROLE_DELETED";
    SET_PENDING_ROLES: "SET_PENDING_ROLES";
};
export default _default;
