declare const _default: {
    RECEIVED_SCHEME: "RECEIVED_SCHEME";
    RECEIVED_SCHEMES: "RECEIVED_SCHEMES";
    CREATED_SCHEME: "CREATED_SCHEME";
    DELETED_SCHEME: "DELETED_SCHEME";
    PATCHED_SCHEME: "PATCHED_SCHEME";
    RECEIVED_SCHEME_TEAMS: "RECEIVED_SCHEME_TEAMS";
    RECEIVED_SCHEME_CHANNELS: "RECEIVED_SCHEME_CHANNELS";
};
export default _default;
