declare const _default: {
    RECEIVED_THREAD: "RECEIVED_THREAD";
    RECEIVED_THREADS: "RECEIVED_THREADS";
    RECEIVED_PER_CHANNEL_MENTION_COUNTS: "RECEIVED_PER_CHANNEL_MENTION_COUNTS";
    FOLLOW_CHANGED_THREAD: "FOLLOW_CHANGED_THREAD";
    READ_CHANGED_THREAD: "READ_CHANGED_THREAD";
    ALL_TEAM_THREADS_READ: "ALL_TEAM_THREADS_READ";
};
export default _default;
