export declare const PostTypes: {
    CHANNEL_DELETED: string;
    CHANNEL_UNARCHIVED: string;
    DISPLAYNAME_CHANGE: string;
    CONVERT_CHANNEL: string;
    EPHEMERAL: string;
    EPHEMERAL_ADD_TO_CHANNEL: string;
    HEADER_CHANGE: string;
    PURPOSE_CHANGE: string;
    JOIN_LEAVE: string;
    JOIN_CHANNEL: string;
    GUEST_JOIN_CHANNEL: string;
    LEAVE_CHANNEL: string;
    ADD_REMOVE: string;
    ADD_TO_CHANNEL: string;
    ADD_GUEST_TO_CHANNEL: string;
    REMOVE_FROM_CHANNEL: string;
    JOIN_TEAM: string;
    LEAVE_TEAM: string;
    ADD_TO_TEAM: string;
    REMOVE_FROM_TEAM: string;
    COMBINED_USER_ACTIVITY: string;
    ME: string;
    ADD_BOT_TEAMS_CHANNELS: string;
    SYSTEM_WARN_METRIC_STATUS: string;
};
declare const _default: {
    POST_CHUNK_SIZE: number;
    POST_DELETED: string;
    SYSTEM_MESSAGE_PREFIX: string;
    SYSTEM_AUTO_RESPONDER: string;
    POST_TYPES: {
        CHANNEL_DELETED: string;
        CHANNEL_UNARCHIVED: string;
        DISPLAYNAME_CHANGE: string;
        CONVERT_CHANNEL: string;
        EPHEMERAL: string;
        EPHEMERAL_ADD_TO_CHANNEL: string;
        HEADER_CHANGE: string;
        PURPOSE_CHANGE: string;
        JOIN_LEAVE: string;
        JOIN_CHANNEL: string;
        GUEST_JOIN_CHANNEL: string;
        LEAVE_CHANNEL: string;
        ADD_REMOVE: string;
        ADD_TO_CHANNEL: string;
        ADD_GUEST_TO_CHANNEL: string;
        REMOVE_FROM_CHANNEL: string;
        JOIN_TEAM: string;
        LEAVE_TEAM: string;
        ADD_TO_TEAM: string;
        REMOVE_FROM_TEAM: string;
        COMBINED_USER_ACTIVITY: string;
        ME: string;
        ADD_BOT_TEAMS_CHANNELS: string;
        SYSTEM_WARN_METRIC_STATUS: string;
    };
    MESSAGE_TYPES: {
        POST: string;
        COMMENT: string;
    };
    MAX_PREV_MSGS: number;
    POST_COLLAPSE_TIMEOUT: number;
    IGNORE_POST_TYPES: string[];
    USER_ACTIVITY_POST_TYPES: string[];
};
export default _default;
