"use strict";
// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
Object.defineProperty(exports, "__esModule", { value: true });
exports.users = exports.websocket = exports.timezone = exports.teams = exports.search = exports.schemes = exports.roles = exports.preferences = exports.posts = exports.jobs = exports.helpers = exports.integrations = exports.gifs = exports.groups = exports.general = exports.files = exports.emojis = exports.errors = exports.cloud = exports.channels = exports.bots = exports.admin = void 0;
var tslib_1 = require("tslib");
var admin = tslib_1.__importStar(require("./admin"));
exports.admin = admin;
var bots = tslib_1.__importStar(require("./bots"));
exports.bots = bots;
var channels = tslib_1.__importStar(require("./channels"));
exports.channels = channels;
var cloud = tslib_1.__importStar(require("./cloud"));
exports.cloud = cloud;
var errors = tslib_1.__importStar(require("./errors"));
exports.errors = errors;
var emojis = tslib_1.__importStar(require("./emojis"));
exports.emojis = emojis;
var files = tslib_1.__importStar(require("./files"));
exports.files = files;
var general = tslib_1.__importStar(require("./general"));
exports.general = general;
var groups = tslib_1.__importStar(require("./groups"));
exports.groups = groups;
var gifs = tslib_1.__importStar(require("./gifs"));
exports.gifs = gifs;
var helpers = tslib_1.__importStar(require("./helpers"));
exports.helpers = helpers;
var integrations = tslib_1.__importStar(require("./integrations"));
exports.integrations = integrations;
var jobs = tslib_1.__importStar(require("./jobs"));
exports.jobs = jobs;
var posts = tslib_1.__importStar(require("./posts"));
exports.posts = posts;
var preferences = tslib_1.__importStar(require("./preferences"));
exports.preferences = preferences;
var roles = tslib_1.__importStar(require("./roles"));
exports.roles = roles;
var schemes = tslib_1.__importStar(require("./schemes"));
exports.schemes = schemes;
var search = tslib_1.__importStar(require("./search"));
exports.search = search;
var teams = tslib_1.__importStar(require("./teams"));
exports.teams = teams;
var timezone = tslib_1.__importStar(require("./timezone"));
exports.timezone = timezone;
var websocket = tslib_1.__importStar(require("./websocket"));
exports.websocket = websocket;
var users = tslib_1.__importStar(require("./users"));
exports.users = users;
//# sourceMappingURL=index.js.map