import { ActionFunc } from "../types/actions";
import { Team, GetTeamMembersOpts, TeamSearchOpts } from "../types/teams";
export declare function selectTeam(team: Team | string): ActionFunc;
export declare function getMyTeams(): ActionFunc;
export declare function getMyTeamUnreads(): ActionFunc;
export declare function getTeam(teamId: string): ActionFunc;
export declare function getTeamByName(teamName: string): ActionFunc;
export declare function getTeams(page?: number, perPage?: number, includeTotalCount?: boolean): ActionFunc;
export declare function searchTeams(term: string, opts?: TeamSearchOpts): ActionFunc;
export declare function createTeam(team: Team): ActionFunc;
export declare function deleteTeam(teamId: string): ActionFunc;
export declare function updateTeam(team: Team): ActionFunc;
export declare function patchTeam(team: Team): ActionFunc;
export declare function regenerateTeamInviteId(teamId: string): ActionFunc;
export declare function getMyTeamMembers(): ActionFunc;
export declare function getTeamMembers(teamId: string, page: number | undefined, perPage: number | undefined, options: GetTeamMembersOpts): ActionFunc;
export declare function getTeamMember(teamId: string, userId: string): ActionFunc;
export declare function getTeamMembersByIds(teamId: string, userIds: string[]): ActionFunc;
export declare function getTeamsForUser(userId: string): ActionFunc;
export declare function getTeamMembersForUser(userId: string): ActionFunc;
export declare function getTeamStats(teamId: string): ActionFunc;
export declare function addUserToTeamFromInvite(token: string, inviteId: string): ActionFunc;
export declare function addUserToTeam(teamId: string, userId: string): ActionFunc;
export declare function addUsersToTeam(teamId: string, userIds: string[]): ActionFunc;
export declare function addUsersToTeamGracefully(teamId: string, userIds: string[]): ActionFunc;
export declare function removeUserFromTeam(teamId: string, userId: string): ActionFunc;
export declare function updateTeamMemberRoles(teamId: string, userId: string, roles: string[]): ActionFunc;
export declare function sendEmailInvitesToTeam(teamId: string, emails: string[]): ActionFunc;
export declare function sendEmailGuestInvitesToChannels(teamId: string, channelIds: string[], emails: string[], message: string): ActionFunc;
export declare function sendEmailInvitesToTeamGracefully(teamId: string, emails: string[]): ActionFunc;
export declare function sendEmailGuestInvitesToChannelsGracefully(teamId: string, channelIds: string[], emails: string[], message: string): ActionFunc;
export declare function getTeamInviteInfo(inviteId: string): ActionFunc;
export declare function checkIfTeamExists(teamName: string): ActionFunc;
export declare function joinTeam(inviteId: string, teamId: string): ActionFunc;
export declare function setTeamIcon(teamId: string, imageData: File): ActionFunc;
export declare function removeTeamIcon(teamId: string): ActionFunc;
export declare function updateTeamScheme(teamId: string, schemeId: string): ActionFunc;
export declare function updateTeamMemberSchemeRoles(teamId: string, userId: string, isSchemeUser: boolean, isSchemeAdmin: boolean): ActionFunc;
export declare function invalidateAllEmailInvites(): ActionFunc;
export declare function membersMinusGroupMembers(teamID: string, groupIDs: string[], page?: number, perPage?: number): ActionFunc;
export declare function getInProductNotices(teamId: string, client: string, clientVersion: string): ActionFunc;
export declare function updateNoticesAsViewed(noticeIds: string[]): ActionFunc;
