import { Group } from "../../types/groups";
import { UserMentionKey } from "./users";
import { GlobalState } from "../../types/store";
import { Dictionary, NameMappedObjects } from "../../types/utilities";
export declare function getAllGroups(state: GlobalState): Dictionary<Group>;
export declare function getMyGroups(state: GlobalState): Dictionary<Group>;
export declare function getAllGroupStats(state: GlobalState): import("../../types/utilities").RelationOneToOne<Group, import("../../types/groups").GroupStats>;
export declare function getGroupStats(state: GlobalState, id: string): import("../../types/groups").GroupStats;
export declare function getGroup(state: GlobalState, id: string): Group;
export declare function getGroupMemberCount(state: GlobalState, id: string): number;
export declare function getGroupTeams(state: GlobalState, id: string): import("../../types/groups").GroupTeam[];
export declare function getGroupChannels(state: GlobalState, id: string): import("../../types/groups").GroupChannel[];
export declare const getAssociatedGroupsByName: (state: GlobalState, teamID: string, channelId: string) => NameMappedObjects<Group>;
export declare const getAssociatedGroupsForReferenceByMention: (state: GlobalState, teamID: string, channelId: string) => Map<string, Group>;
export declare function searchAssociatedGroupsForReferenceLocal(state: GlobalState, term: string, teamId: string, channelId: string): Group[];
export declare function getAssociatedGroupsForReference(state: GlobalState, teamId: string, channelId: string): Group[];
export declare const getGroupsNotAssociatedToTeam: (state: GlobalState, teamID: string) => Group[];
export declare const getGroupsAssociatedToTeam: (state: GlobalState, teamID: string) => Group[];
export declare const getGroupsNotAssociatedToChannel: (state: GlobalState, channelID: string, teamID: string) => Group[];
export declare const getGroupsAssociatedToChannel: (state: GlobalState, channelID: string) => Group[];
export declare const getGroupsAssociatedToTeamForReference: (state: GlobalState, teamID: string) => Group[];
export declare const getGroupsAssociatedToChannelForReference: (state: GlobalState, channelID: string) => Group[];
export declare const getAllAssociatedGroupsForReference: (state: GlobalState) => Group[];
export declare const getAllGroupsForReferenceByName: (state: GlobalState) => NameMappedObjects<Group>;
export declare const getMyAllowReferencedGroups: (state: GlobalState) => Group[];
export declare const getMyGroupsAssociatedToChannelForReference: (state: GlobalState, teamId: string, channelId: string) => Group[];
export declare const getMyGroupMentionKeys: (state: GlobalState) => UserMentionKey[];
export declare const getMyGroupMentionKeysForChannel: (state: GlobalState, teamId: string, channelId: string) => UserMentionKey[];
