import { GlobalState } from "../../types/store";
import { Team, TeamMembership, TeamStats } from "../../types/teams";
import { UserProfile } from "../../types/users";
import { $ID, IDMappedObjects, RelationOneToOne } from "../../types/utilities";
export declare function getCurrentTeamId(state: GlobalState): string;
export declare function getTeamByName(state: GlobalState, name: string): Team | undefined;
export declare function getTeams(state: GlobalState): IDMappedObjects<Team>;
export declare function getTeamsInPolicy(state: GlobalState): IDMappedObjects<Team>;
export declare function getTeamStats(state: GlobalState): RelationOneToOne<Team, TeamStats>;
export declare function getTeamMemberships(state: GlobalState): import("../../types/utilities").Dictionary<TeamMembership>;
export declare function getMembersInTeams(state: GlobalState): RelationOneToOne<Team, RelationOneToOne<UserProfile, TeamMembership>>;
export declare const getTeamsList: (state: GlobalState) => Team[];
export declare const getCurrentTeam: (state: GlobalState) => Team;
export declare function getTeam(state: GlobalState, id: string): Team;
export declare const getCurrentTeamMembership: (state: GlobalState) => TeamMembership;
export declare const isCurrentUserCurrentTeamAdmin: (state: GlobalState) => boolean;
export declare const getCurrentTeamUrl: (state: GlobalState) => string;
export declare const getCurrentRelativeTeamUrl: (state: GlobalState) => string;
export declare const getCurrentTeamStats: (state: GlobalState) => TeamStats;
export declare const getMyTeams: (state: GlobalState) => Team[];
export declare const getMyTeamMember: (state: GlobalState, teamId: string) => TeamMembership;
export declare const getMembersInCurrentTeam: (state: GlobalState) => RelationOneToOne<UserProfile, TeamMembership>;
export declare function getTeamMember(state: GlobalState, teamId: string, userId: string): TeamMembership | null;
export declare const getListableTeamIds: (state: GlobalState) => Array<$ID<Team>>;
export declare const getListableTeams: (state: GlobalState) => Team[];
export declare const getSortedListableTeams: (state: GlobalState, locale: string) => Team[];
export declare const getJoinableTeamIds: (state: GlobalState) => Array<$ID<Team>>;
export declare const getJoinableTeams: (state: GlobalState) => Team[];
export declare const getSortedJoinableTeams: (state: GlobalState, locale: string) => Team[];
export declare const getMySortedTeamIds: (state: GlobalState, locale: string) => Array<$ID<Team>>;
export declare function getMyTeamsCount(state: GlobalState): number;
export declare const getChannelDrawerBadgeCount: (state: GlobalState) => number;
export declare function makeGetBadgeCountForTeamId(): (state: GlobalState, id: string) => number;
